services:
  postgresql:
    image: postgres:16.0-alpine
    container_name: predico_postgresql
    restart: always
    env_file:
      - api/.dev.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - predico_network

  app: &api
    build: api
    container_name: predico_rest_app
    environment:
      - WAIT_HOSTS=postgresql:5432
    restart: unless-stopped
    command: gunicorn -c gunicorn.conf api.wsgi:application --forwarded-allow-ips="*" -b :8000
    depends_on:
      - postgresql
    env_file:
      - api/.env
    networks:
      - predico_network
    volumes:
      - static_volume:/usr/src/django/api/staticfiles
      - media_volume:/usr/src/django/api/mediafiles

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        REACT_APP_API_URL: https://predico-elia.inesctec.pt/api/v1
    container_name: predico_frontend_build
    networks:
      - predico_network
    volumes:
      - frontend_build:/app/build  # This volume will store the build output

  nginx:
    container_name: predico_rest_nginx
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443" # HTTPS
    depends_on:
      - app
      - frontend
    networks:
      - predico_network
    volumes:
      - frontend_build:/usr/share/nginx/html  # Correcting the path for admin frontend
      - static_volume:/usr/src/django/api/staticfiles  # Serve Django static files correctly
      - media_volume:/usr/src/django/api/mediafiles    # Serve Django media files

volumes:
  frontend_build:
  postgresql-data:
  static_volume:
  media_volume:

networks:
  predico_network:
    driver: bridge
