services:
  postgresql:
    image: postgres:16.0-alpine
    container_name: predico_postgresql
    restart: always
    env_file:
      - api/.dev.env
    ports:
      - "5432:5432"
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      
volumes:
  postgresql-data:
