services:
  postgresql:
    image: postgres:16.0-alpine
    container_name: predico_postgresql
    restart: always
    env_file:
      - api/.dev.env
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - predico_network

  app: &api
    build: api
    container_name: predico_rest_app
    environment:
      - WAIT_HOSTS=postgresql:5432
    restart: unless-stopped
    command: gunicorn -c gunicorn.conf api.wsgi:application --forwarded-allow-ips="*" -b :8000
    depends_on:
      - postgresql
    env_file:
      - api/.dev.env
    networks:
      - predico_network
    volumes:
      - static_volume:/usr/src/django/api/staticfiles
      - media_volume:/usr/src/django/api/mediafiles

  nginx:
    container_name: predico_rest_nginx
    restart: unless-stopped
    build:
      context: nginx
      dockerfile: Dockerfile
    ports:
      - "443:443"
    depends_on:
      - app
    networks:
      - predico_network
    volumes:
      - static_volume:/usr/src/api/staticfiles
      - media_volume:/usr/src/api/mediafiles

volumes:
  postgresql-data:
  static_volume:
  media_volume:

networks:
  predico_network:
    driver: bridge