# Generated by Django 3.2 on 2024-06-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rawdata',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userresources'),
        ),
        migrations.AddField(
            model_name='rawdata',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='individualforecasts',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userresources'),
        ),
        migrations.AddField(
            model_name='individualforecasts',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='rawdata',
            unique_together={('user', 'resource', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='individualforecasts',
            unique_together={('user', 'resource', 'variable', 'datetime')},
        ),
    ]
