# Generated by Django 3.2 on 2024-06-19 23:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('open_ts', models.DateTimeField(auto_now_add=True)),
                ('close_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('launch_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('finish_ts', models.DateTimeField(blank=True, default=None, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('running', 'Running'), ('finished', 'Finished')], default='open', max_length=10)),
            ],
            options={
                'db_table': 'market_session',
            },
        ),
        migrations.CreateModel(
            name='MarketSessionChallenge',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('use_case', models.CharField(choices=[('wind_power', 'Wind Forecast'), ('wind_power_ramp', 'Wind Ramp Forecast')], default='wind_power_ramp', max_length=18)),
                ('start_datetime', models.DateTimeField()),
                ('end_datetime', models.DateTimeField()),
                ('target_day', models.DateField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_session_challenge',
            },
        ),
        migrations.CreateModel(
            name='MarketSessionEnsemble',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('model', models.CharField(choices=[('GBR', 'Gbr'), ('weighted_avg', 'Weighted Avg'), ('eq_weights', 'Eq Weights'), ('LR', 'Lr')], max_length=20)),
                ('variable', models.CharField(choices=[('q05', 'Q05'), ('q10', 'Q10'), ('q20', 'Q20'), ('q30', 'Q30'), ('q40', 'Q40'), ('q50', 'Q50'), ('q60', 'Q60'), ('q70', 'Q70'), ('q80', 'Q80'), ('q90', 'Q90'), ('q95', 'Q95')], max_length=5)),
                ('weights', models.JSONField(blank=True, null=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_session_ensemble',
            },
        ),
        migrations.CreateModel(
            name='MarketSessionEnsembleForecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'market_session_ensemble_forecasts',
            },
        ),
        migrations.CreateModel(
            name='MarketSessionSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('variable', models.CharField(choices=[('q05', 'Q05'), ('q10', 'Q10'), ('q20', 'Q20'), ('q30', 'Q30'), ('q40', 'Q40'), ('q50', 'Q50'), ('q60', 'Q60'), ('q70', 'Q70'), ('q80', 'Q80'), ('q90', 'Q90'), ('q95', 'Q95'), ('point', 'Point')], max_length=5)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('market_session_challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionchallenge')),
            ],
            options={
                'db_table': 'market_session_submission',
            },
        ),
        migrations.CreateModel(
            name='MarketSessionSubmissionForecasts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('value', models.FloatField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionsubmission')),
            ],
            options={
                'db_table': 'market_session_submission_forecasts',
            },
        ),
    ]
