# Generated by Django 3.2 on 2024-06-19 23:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marketsessionsubmission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='marketsessionensembleforecasts',
            name='ensemble',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionensemble'),
        ),
        migrations.AddField(
            model_name='marketsessionensemble',
            name='market_session_challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionchallenge'),
        ),
        migrations.AddField(
            model_name='marketsessionchallenge',
            name='market_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsession'),
        ),
        migrations.AddField(
            model_name='marketsessionchallenge',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userresources'),
        ),
        migrations.AddField(
            model_name='marketsessionchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='marketsession',
            unique_together={('id', 'open_ts')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsessionsubmissionforecasts',
            unique_together={('submission', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsessionsubmission',
            unique_together={('user', 'variable', 'market_session_challenge')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsessionensembleforecasts',
            unique_together={('ensemble', 'datetime')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsessionensemble',
            unique_together={('market_session_challenge', 'model', 'variable')},
        ),
        migrations.AlterUniqueTogether(
            name='marketsessionchallenge',
            unique_together={('market_session', 'user', 'resource')},
        ),
    ]
