# Generated by Django 5.1.1 on 2024-10-10 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSessionSubmissionScores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric', models.CharField(choices=[('pinball', 'Pinball'), ('mae', 'Mae'), ('rmse', 'Rmse')], max_length=10)),
                ('value', models.FloatField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionsubmission')),
            ],
            options={
                'db_table': 'market_session_submission_scores',
                'unique_together': {('submission', 'metric')},
            },
        ),
    ]
