# Generated by Django 5.1.1 on 2024-10-12 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_marketsessionensembleweights'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketsessionensemble',
            name='weights',
        ),
    ]
