# Generated by Django 5.1.1 on 2024-10-19 21:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0005_remove_marketsessionensemble_weights'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketsession',
            name='open_ts',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
