# Generated by Django 5.1.1 on 2024-10-30 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0006_alter_marketsession_open_ts'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketSessionRampAlerts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField()),
                ('model', models.CharField(max_length=30)),
                ('cluster_id', models.IntegerField()),
                ('iqw', models.FloatField()),
                ('consecutive_count', models.IntegerField()),
                ('variability_quantiles', models.JSONField()),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market.marketsessionchallenge')),
            ],
            options={
                'db_table': 'market_session_ramp_alerts',
                'unique_together': {('challenge', 'datetime')},
            },
        ),
    ]
