site_name: Predico
theme:
  name: material
  logo: null
  custom_dir: overrides
  highlightjs: true
  features:
    - navigation.expand
    - navigation.sections
    - navigation.instant
    - code-copy
    - content.code.copy
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
extra_css:
  - extra.css
nav:
  - Home: index.md
  - Introduction: introduction.md
  - Getting Started: getting_started.md
  - Forecaster Application: application.md
  - Forecaster Interactions:
      - Authentication: authentication.md
      - Listing Open Sessions: listing_open_sessions.md
      - Listing Challenges: listing_challenges.md
      - Downloading Raw Data: downloading_raw_data.md
      - Preparing a Forecast: preparing_forecast.md
      - Submitting a Forecast: submitting_forecast.md
      - Submitting Historical Forecasts (First Time Only): submitting_historical_forecasts.md
      - Listing Submissions: listing_submissions.md
      - Listing Submission Scores: listing_submissions_scores.md
      - Listing Submission Contributions: listing_submissions_contributions.md
      - Listing Historical Forecasts: listing_historical_forecasts.md
  - Other:
    - Contacts: contacts.md
    - Useful Links: useful_links.md
    - FAQ: faq.md
markdown_extensions:
  - pymdownx.snippets
  - tables
  - codehilite
  - admonition
  - attr_list
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.details
  - pymdownx.tabbed
  - toc:
      permalink: true
